# Generated by Django 5.2.8 on 2025-11-28 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('importance', models.IntegerField(help_text='1-10 scale', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('priority_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='blocking', to='tasks.task')),
            ],
        ),
    ]
